### PR TITLE
Added ... to taking numbers out of array in README

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by mythz** [comment]
this will also needs to change to ...2 to match

**Comment by mythz** [comment]
Cheers :+1:

**Comment by jchannon** [comment]
No worries!

Any plans to do a Swift web fwk or you going to let someone take the pain?
:smile:

**Comment by mythz** [comment]
@jchannon Not in the near future, already have my work cut out for me for working on ASP.NET 5 port of ServiceStack after the betas and once the platform has stabalized. 

The issue with Swift on the server being so young is that it needs a robust and low-level http middleware framework to build a high-level webfx on top of. Ideally this would come from Apple so it can quickly become a defacto standard. Trying to build something too early over TCP is at major risk of a wasted efforts rewrite.

**Comment by jchannon** [comment]
Agreed, its very early but it will be interesting to see the potential I
personally see actually evolves

**Comment by mythz** [comment]
Yep I'd expect the server story to materialize and accelerate quickly after the OSS Swift 2.0 is released and supported on Linux.

**Pull request merged**
